### PR TITLE
Fix an issue that was preventing the edit of a registry record containing a "/" in its name

### LINKED ISSUE #51: Registry records containing a "/" are not editable TTW
See also https://github.com/plone/Products.CMFPlone/issues/3296

Fixes https://github.com/plone/Products.CMFPlone/issues/3296

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #51
Fixes plone/Products.CMFPlone#3296

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Stupid me, I added a changelog in the changes file :facepalm:, I will move it to a towncrier entry

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Pull request merged**
