### PR TITLE
Require setuptools 68.2+ for building the package.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Configuring with plone/meta.

This uses https://github.com/plone/meta/pull/184

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I cancelled the jobs, and rebased and force pushed.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
That went wrong.  Try again.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@gforcada There is one pending Jenkins check, but it points to [PR 6.1 3.8](https://jenkins.plone.org/job/pull-request-6.1-3.8/build?delay=0sec) and this gives a 404.

Do you know what needs to be fixed?

**Comment by gforcada** [comment]
Sorry, I forgot to create the Jenkins job 😕 it's created now 👍🏾

**Review by gforcada — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Thanks!

**Pull request merged**
