### PR TITLE
Revert "Tests for choice schema constraints"

### PR DESCRIPTION
**Pull request by gforcada**
Reverts plone/plone.app.registry#18

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens @metatoaster I'm going to merge this one if tests pass. Currently 5.0 build is broken due to #18 having been merged.

As it was just about adding some tests, maybe there's a dependency that can no longer be shared between 5.0 and 5.1?

**Comment by mauritsvanrees** [comment]
+1

**Comment by metatoaster** [comment]
@gforcada Well I guess these tests should only have been merged onto the 5.1 branch originally (if there was one) as the code that fixed this issue only got accepted into there only, not 5.0 and earlier as per plone/plone.supermodel#12.  If the tests are fixed in 5.0 due to the changes by that maybe we can re-merge these tests back in, I guess? @jensens what do you think?

**Comment by jensens** [comment]
@metatoaster indeed :/ i think backporting is a good idea.

**Pull request merged**
