### PR TITLE
Various registry improvements

### PR DESCRIPTION
**Pull request by vangheem**
Changes include:
- being able to split registry.xml files into multiple files
- provide import/export in control panel
- provide ability to delete record in control panel
- provide ability to add new record in control panel

These are various things that have been annoying me about plone.app.registry. Is there a plip that someone is working on already?

### CODE REVIEW

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.0/977/

**Comment by vangheem** [comment]
Tests pass but this needs some review to see if others agree with this feature. For me, it's really annoying how large my registry.xml files are getting now and it'd be great to be able to split them into many files.

**Comment by gforcada** [comment]
:+1: with the PLIP about being able to export each control panel configuration alone it will be really useful.

**Comment by jensens** [comment]
big  +1 - but I think this should go through the PLIP process, @vangheem may you turn it into  a plip? I'd second it. If its ready on March 1st it can be discussed at FWT meeting.

**Comment by ebrehault** [comment]
I love it.

2 comments:

- I guess it will imply to fix this:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/resources/exportimport/bundles.py#L16
(because if the bundles are not defined in `registry.xml` but in `registry/whatever.xml`, it won't work)

- you propose we split `registry.xml` freely (we can name the files the way we want, we can put any registry entry in them). I like the fact it is flexible. But users will probably split stuff on a structured and semantic way (for instance, one file with the resources and bundles, one for the portlets, one for the locales and i18n, etc.). So we will end up with a new sub folder in GS profiles, containing similar filenames than the ones already in our profiles (viewlets.xml, controlpanel.xml, etc.) and it might be confusing. It does not mean this PLIP is not useful (it is very useful), but at some point we will have to restructure the GS profiles in a more simple and meaningful way.

**Comment by jensens** [comment]
Quick Check:
- needs a rebase
- then needs test run

@vangheem: I'll do a official review as soon as you consider this as ready.

**Comment by idgserpro** [comment]
> but at some point we will have to restructure the GS profiles in a more simple and meaningful way.

@ebrehault Some ideas in https://github.com/plone/Products.CMFPlone/issues/1137#issuecomment-146216663

**Comment by tkimnguyen** [comment]
Is that mister roboto thing for real?

**Comment by idgserpro** [comment]
> nathan.vangheem your emails are not known to GithHb and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

> Is that mister roboto thing for real?

Does it handle github's [private email addresses](https://help.github.com/articles/keeping-your-email-address-private/)?

**Comment by jensens** [comment]
@tkimnguyen looks like @vangheem has used a different identifier than registered at github. @vangheem are you able to correct this?

**Comment by vangheem** [comment]
It was fixed long ago. I think mr.roboto is re-reading the old commit.

and @tkimnguyen it's not like mr.roboto's messages are enforced. It can still in deed be merged. Nothing to be frightened about.

**Comment by vangheem** [comment]
tests:
- http://jenkins.plone.org/job/pull-request-5.1/768/
- http://jenkins.plone.org/job/pull-request-5.0/1515/

**Comment by vangheem** [comment]
This should be ready for review/merge.

**Comment by gforcada** [comment]
Thanks kim for the docs!

Is p.a.registry docs pulled in docs.plone.org? I guess we can already merge right?

**Comment by tkimnguyen** [comment]
thx for the merge :) 

@gforcada doesn't look like docs.plone.org has the p.a.registry readme and what's there looks out of date in at least one of the early search results which refers to "the state of the art way to do it in Plone 4"

**Comment by gforcada** [comment]
@tkimnguyen would you mind then creating a ticket on documentation repo to track this? If we have docs but they are nowhere to be found is a bit pointless :-)

**Comment by gforcada** [comment]
@tkimnguyen scrap that, now I see https://github.com/plone/documentation/issues/816 thanks!

**Comment by mauritsvanrees** [comment]
I made a release with this: https://pypi.python.org/pypi/plone.app.registry/1.6

**Comment by tkimnguyen** [comment]
@mauritsvanrees I must have bungled something in my references to the screen shots because on https://pypi.python.org/pypi/plone.app.registry/1.6 they are missing

**Comment by mauritsvanrees** [comment]
@tkimnguyen Your image references worked fine locally, but not on PyPI. I have fixed this in commit e19cd30cba397ecf980679f89b00f84abdd3fd14 to point to the raw contents of the master branch. It's a bit less nice, because if you change or add a screen shot, you can only see the result after you have pushed your changes. But this seems the most practical.
I have released 1.6.1 and PyPI shows screen shots now. Thank you for adding them!

**Comment by tkimnguyen** [comment]
noted for future reference! thx

**Pull request merged**
